### ISSUE TITLE
Realizar maqueta de prototipo (Bocetos)

### ISSUE THREAD

**Issue by amelissagomez** [ISWPOLI/edugame#12]
**Realizar maqueta de prototipo (Bocetos)**
Animaciones y enlace de pantallas del prototipo

**Tareas**
- [x] Crear bocetos 
- [x] Enlaces entre pantallas
- [x] Definir formulario de inicio de sesión
- [x] Definir formulario de registro
- [x] Definir Información de profesores
- [x] Definir información de estudiantes
- [x] Definir información de materia

**Comment by rahermes** [comment]
Se adjunta el Mokup del login del aplicativo

**Comment by amelissagomez** [comment]
Se adjuntan bocetos de juegos, mapas del juego @amauric30  y información por perfiles.
