### ISSUE TITLE
Estructura de firebase e integración con Android studio:

### ISSUE THREAD

**Issue by amauric30** [ISWPOLI/edugame#8]
- Agrega una huella digital de SHA1 de la versión para apps de Android en Firebase console (para ID de cliente de Oauth)para android.
- Actualiza el ID de App Store, el ID de paquete y el ID de equipo (si es necesario) de tus apps de iOS.
- Agrega una lista blanca para tus dominios a fin de evitar el uso no autorizado.
Incluye en la lista blanca tu dominio de producción para claves de API, además de los ID de cliente en Google Developers Console. - Incluye en la lista blanca el dominio de producción en la pestaña Auth del panel de Firebase console.
- Funciones de Realtime Database, Storage y Hosting tienen límites de uso estrictos en los planes Spark y Flame.
-  Preparar servicios Remote Config:
- Definición y configuración de las reglas de RemoteConfig a los usuarios de la versión y los valores predeterminados adecuados se distribuyan en las apps de Poli-game.
- Define los parámetros de público, a fin de que Analytics comience a reunir usuarios desde el lanzamiento.
- Subir archivos proguard para compilaciones de liberación a fin de usarlos en  CrashReporting. Habilita la vinculación a BigQuery si planeas usar BigQuery con los datos de Analytics.
- CloudMessaging:
- Para Cloud Messaging en iOS,  certificado APNS subido y desactivar la zona de pruebas en las compilaciones de liberación.
-  CrashReporting:
- . Subir asignaciones proguard para compilaciones de liberación a fin de usarlas en CrashReporting para android.
-  Subir un archivo dsym para compilaciones de liberación a fin de usarlo en Crash Reporting para ios.
-   Realtime Database:
-  Configurar las reglas proguard para que funcionen con Realtime Database para android.
-  Configurar reglas de Firebase Database para evitar el acceso no intencional a datos.
-  Escalamiento de Realtime Database con una cuota predeterminada lo suficientemente grande para las aplicaciones de Poli-game.
- Storage:
- Configurar las reglas de seguridad de Storage para evitar el acceso no intencional a datos.
-  Authentication:
-  Configurar archivos proguard para que funcionen con Authentication para android.
- Manejo de errores en iOS.
-  Desactivar los usuarios anónimos en Firebase console.
-  Liberación:
- Probar los apps de Android de poli-game en Test Lab para verificar que no haya errores.
-  Crear Dynamic Links para nuevas funciones clave a fin de usarlos en material promocional y medios sociales.
  Authentication:
-  Configurar archivos proguard para que funcionen con Authentication para android.
-  Manejo de errores en iOS.
-  Desactivar los usuarios anónimos en Firebase console.
-  Liberación:
-  Probar los apps de Android de poli-game en Test Lab para verificar que no haya errores.
- Crear Dynamic Links para nuevas funciones clave a fin de usarlos en material promocional y medios sociales.

**Comment by rahermes** [comment]
No se maneja un modelo relacional debido a que firebase es una base de datos no relacional, por tal motivo no se manejan tablas.
